---
groups:
- name: cf-tweets-fetcher-app
  jobs:
  - unit-tests
  - deploy-application
  - tag
  - github-release

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: app-source
    trigger: true
  - task: unit-tests
    file: app-source/ci/tasks/unit-tests.yml
    on_failure:
      put: failure-alert
      params:
        channel:  {{slack-channel}}
        username: Concourse CI
        icon_url: https://i.imgur.com/eioobYI.png
        text:     {{slack-failed-text}}
- name: deploy-application
  serial: true
  public: true
  plan:
  - get: app-source
    passed:
    - unit-tests
    trigger: true
  - put: resource-deploy-app
    params:
      manifest: app-source/ci/manifest/manifest.yml
      environment_variables:
        TWITTER_CONSUMER_KEY: {{twitter-consumer-key}}
        TWITTER_CONSUMER_SECRET: {{twitter-consumer-secret}}
        TWITTER_CONSUMER_ACCESS_TOKEN: {{twitter-consumer-access-token}}
        TWITTER_CONSUMER_ACCESS_SECRET: {{twitter-consumer-access-secret}}
        GOOGLE_MAPS_KEY: {{google-maps-key}}
    on_failure:
      put: failure-alert
      params:
        channel:  {{slack-channel}}
        username: Concourse CI
        icon_url: https://i.imgur.com/eioobYI.png
        text:     {{slack-failed-text}}
- name: tag
  public: true
  serial: true
  plan:
  - get: app-source
    passed:
    - deploy-application
    trigger: true
  - put: version
    params: {bump: minor}
  - put: app-source
    params:
      only_tag: true
      repository: app-source
      tag: version/number
    on_failure:
      put: failure-alert
      params:
        channel:  {{slack-channel}}
        username: Concourse CI
        icon_url: https://i.imgur.com/eioobYI.png
        text:     {{slack-failed-text}}
- name: github-release
  public: true
  serial: true
  plan:
  - get: app-source
    passed:
    - tag
    trigger: true
  - get: version
  - put: github-release
    params:
      name: version/number
      tag: version/number
    on_success:
      put: announcement
      params:
        channel:  {{slack-channel}}
        username: Concourse CI
        icon_url: https://i.imgur.com/eioobYI.png
        text:     {{slack-success-text}}
    on_failure:
      put: failure-alert
      params:
        channel:  {{slack-channel}}
        username: Concourse CI
        icon_url: https://i.imgur.com/eioobYI.png
        text:     {{slack-failed-text}}

resources:
- name: app-source
  type: git
  source:
    uri: git@github.com:Altoros/tweets-fetcher.git
    branch: master
    private_key: {{github-private-key}}
- name: failure-alert
  type: slack-notification
  source:
    url: {{slack-url}}
- name: announcement
  type: slack-notification
  source:
    url: {{slack-url}}
- name: resource-deploy-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-user}}
    password: {{cf-pass}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: false
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:Altoros/tweets-fetcher.git
    branch: version
    file: version
    private_key: {{github-private-key}}
    git_user: {{git-email}}
- name: github-release
  type: github-release
  source:
    user: Altoros
    repository: tweets-fetcher
    access_token: {{github-access-token}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
